### ISSUE TITLE
a nil value

### ISSUE THREAD

**Issue by Meridaw** [Road-block/ArchiTotem#5]
![issue archi totem](https://user-images.githubusercontent.com/26133646/34461462-214e7c20-ee2b-11e7-8ffd-398a813954a9.png)

**Comment by Meridaw** [comment]
![issue archi totem2](https://user-images.githubusercontent.com/26133646/34461486-b93b658e-ee2b-11e7-8b23-859bc373f899.png)

**Comment by Meridaw** [comment]
Got the first one at game start, and the chat info when i mouseover the totem bar.

**Comment by Road-block** [comment]
What language client?  
I'll fix them anyway, just curious.  
Is it French?

**Comment by Road-block** [comment]
Give [89bdd8d](https://github.com/Road-block/ArchiTotem/archive/master.zip) a try and report back.

**Comment by Meridaw** [comment]
English. It works great now with the new build. I just wanted to check the addon out on my shaman alt, and make some pictures for the github list.

**Comment by Road-block** [comment]
[v1.41](https://github.com/Road-block/ArchiTotem/tree/1.41-11200)
